name = "aoc"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
party = ">= 1.0.4 and < 2.0.0"
clip = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.0.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleamy_structures = ">= 1.1.0 and < 2.0.0"
iv = ">= 1.3.2 and < 2.0.0"

[dev-dependencies]
qcheck = ">= 1.0.0 and < 2.0.0"
unitest = ">= 1.0.0 and < 2.0.0"
